import type { EvidenceItem } from "./types";

export const MOCK_EVIDENCE_ITEMS: EvidenceItem[] = [
  {
    id: "01",
    name: "CCTV_Footage_01.mp4",
    description: "Entrance camera footage",
    type: "Video",
    source: "CCTV",
    addedBy: {
      name: "Arjun Karthik",
      avatar: "/images/avatar-investigator.jpg",
      initials: "AK",
    },
    dateAdded: "Oct 5, 2026",
    timeAdded: "11:32 AM",
    status: "Verified",
    fileSize: "128.4 MB",
    hash: "3f2a...9c7e",
    location: "/evidence/2026/fx-184/",
    thumbnailType: "cctv",
    previewImage: "/images/cctv-suspect.jpg",
    camId: "CAM 01",
    timestamp: "2026-10-04 21:14:32",
    fullDescription:
      "Entrance camera footage showing suspect entering the store.",
    aiAnalysis: {
      score: 87,
      title: "Face Match Detected",
      subtitle: "Possible match with existing record in criminal database.",
      attributes: [
        "1 Face Detected",
        "Male, 25-35 years",
        "Black Hoodie",
        "Medium Build",
      ],
    },
  },
  {
    id: "02",
    name: "Fingerprint_01.jpg",
    description: "Fingerprint from door handle",
    type: "Image",
    source: "Crime Scene",
    addedBy: {
      name: "Priya Nair",
      avatar: "/images/avatar-analyst.jpg",
      initials: "PN",
    },
    dateAdded: "Oct 5, 2026",
    timeAdded: "10:18 AM",
    status: "Verified",
    fileSize: "4.2 MB",
    hash: "a81b...4c2d",
    location: "/evidence/2026/fx-184/biometrics/",
    thumbnailType: "fingerprint",
    fullDescription:
      "Latent fingerprint lifted from store entrance glass door handle using ninhydrin developer.",
    aiAnalysis: {
      score: 94,
      title: "Fingerprint Match Identified",
      subtitle: "AFIS candidate match verified with 12 minutiae points.",
      attributes: [
        "Right Index Finger",
        "Whorl Pattern",
        "12 Minutiae Points",
        "High Clarity Scan",
      ],
    },
  },
  {
    id: "03",
    name: "Suspect_Image_02.jpg",
    description: "Suspect captured on CCTV",
    type: "Image",
    source: "CCTV",
    addedBy: {
      name: "Arjun Karthik",
      avatar: "/images/avatar-investigator.jpg",
      initials: "AK",
    },
    dateAdded: "Oct 4, 2026",
    timeAdded: "11:46 PM",
    status: "Under Review",
    fileSize: "8.6 MB",
    hash: "e3d7...1a5f",
    location: "/evidence/2026/fx-184/stills/",
    thumbnailType: "suspect",
    previewImage: "/images/cctv-suspect.jpg",
    camId: "CAM 02",
    timestamp: "2026-10-04 21:14:48",
    fullDescription:
      "Enhanced still frame showing suspect fleeing along North Boag Road corridor.",
    aiAnalysis: {
      score: 76,
      title: "Partial Face Recognition",
      subtitle: "AI enhancement running on low-light facial profile.",
      attributes: [
        "Obscured Profile",
        "Dark Hooded Jacket",
        "Estimated Height: 5'10\"",
        "Low Contrast Lighting",
      ],
    },
  },
  {
    id: "04",
    name: "Witness_Statement.pdf",
    description: "Statement from store manager",
    type: "Document",
    source: "Investigator",
    addedBy: {
      name: "Priya Nair",
      avatar: "/images/avatar-analyst.jpg",
      initials: "PN",
    },
    dateAdded: "Oct 4, 2026",
    timeAdded: "10:05 PM",
    status: "Verified",
    fileSize: "1.8 MB",
    hash: "9c4b...77e2",
    location: "/evidence/2026/fx-184/documents/",
    thumbnailType: "document",
    fullDescription:
      "Sworn deposition transcribed by duty officer; confirms suspect arrival time and weapon.",
    aiAnalysis: {
      score: 91,
      title: "NLP Consistency Score",
      subtitle: "Cross-verified timeline aligns with dispatch emergency logs.",
      attributes: [
        "Key Witness: Store Manager",
        "Weapon: Semi-Automatic",
        "Timeline Match: 99%",
        "Digitally Signed",
      ],
    },
  },
  {
    id: "05",
    name: "Weapon_01.jpg",
    description: "Recovered handgun",
    type: "Image",
    source: "Crime Scene",
    addedBy: {
      name: "Arjun Karthik",
      avatar: "/images/avatar-investigator.jpg",
      initials: "AK",
    },
    dateAdded: "Oct 4, 2026",
    timeAdded: "09:50 PM",
    status: "Flagged",
    fileSize: "14.2 MB",
    hash: "6b81...00f4",
    location: "/evidence/2026/fx-184/ballistics/",
    thumbnailType: "weapon",
    fullDescription:
      "Black 9mm semi-automatic handgun recovered near dumpster alleyway with serial partially defaced.",
    aiAnalysis: {
      score: 98,
      title: "Ballistics & Object Match",
      subtitle: "Detected 9mm firearm matching casing calibers collected at scene.",
      attributes: [
        "Caliber: 9mm Luger",
        "Defaced Serial Area",
        "Fingerprint Traces Found",
        "High Priority Flag",
      ],
    },
  },
  {
    id: "06",
    name: "Audio_Clip_01.wav",
    description: "Emergency call recording",
    type: "Audio",
    source: "Phone Record",
    addedBy: {
      name: "System",
      avatar: undefined,
      initials: "SY",
    },
    dateAdded: "Oct 4, 2026",
    timeAdded: "09:40 PM",
    status: "Verified",
    fileSize: "5.4 MB",
    hash: "11da...98a3",
    location: "/evidence/2026/fx-184/audio/",
    thumbnailType: "audio",
    fullDescription:
      "Emergency police hotline dispatch call recorded during the active incident.",
    aiAnalysis: {
      score: 83,
      title: "Acoustic Diarization",
      subtitle: "Detected distress vocal markers and secondary male voice background audio.",
      attributes: [
        "2 Distinct Speakers",
        "Stress Level: Critical",
        "Store Bell Audible",
        "Duration: 02:44 min",
      ],
    },
  },
  {
    id: "07",
    name: "Store_Receipt.jpg",
    description: "Transaction receipt",
    type: "Image",
    source: "Crime Scene",
    addedBy: {
      name: "Priya Nair",
      avatar: "/images/avatar-analyst.jpg",
      initials: "PN",
    },
    dateAdded: "Oct 4, 2026",
    timeAdded: "09:28 PM",
    status: "Under Review",
    fileSize: "3.1 MB",
    hash: "44fe...31ca",
    location: "/evidence/2026/fx-184/receipts/",
    thumbnailType: "receipt",
    fullDescription:
      "Paper cash register audit slip from Till #2 showing last transaction prior to robbery.",
    aiAnalysis: {
      score: 89,
      title: "OCR Text Extraction",
      subtitle: "Extracted register transaction total, cashier ID, and timestamp.",
      attributes: [
        "Till #02 Register",
        "Total: $418.50",
        "Timestamp: 21:12:45",
        "Barcode Validated",
      ],
    },
  },
  {
    id: "08",
    name: "Vehicle_Image_01.jpg",
    description: "Suspect vehicle",
    type: "Image",
    source: "CCTV",
    addedBy: {
      name: "Arjun Karthik",
      avatar: "/images/avatar-investigator.jpg",
      initials: "AK",
    },
    dateAdded: "Oct 4, 2026",
    timeAdded: "09:20 PM",
    status: "Verified",
    fileSize: "11.3 MB",
    hash: "ff09...88e1",
    location: "/evidence/2026/fx-184/vehicles/",
    thumbnailType: "vehicle",
    camId: "CAM 04",
    timestamp: "2026-10-04 21:15:30",
    fullDescription:
      "Silver sedan observed idling near rear loading bay around time of getaway.",
    aiAnalysis: {
      score: 85,
      title: "ANPR & Vehicle Classifier",
      subtitle: "Automated license plate reader query matched suspect vehicle make.",
      attributes: [
        "Make: Hyundai Sedan",
        "Color: Silver / Grey",
        "Partial Plate: TN-09-**",
        "Rear Quarter Dent",
      ],
    },
  },
];
