import type { SuspectItem } from "./types";

export const INITIAL_SUSPECTS: SuspectItem[] = [
  {
    id: "susp-01",
    numberIndex: "01",
    name: "Arun Prakash",
    alias: "Alias: Arun, Rocky",
    photo: "/images/suspects/arun-prakash.jpg",
    status: "Primary Suspect",
    role: "Direct Involvement",
    matchConfidence: 92,
    lastSeenDate: "Oct 4, 2026",
    lastSeenTime: "09:14 PM",
    dob: "May 12, 1992",
    age: 34,
    gender: "Male",
    nationality: "Indian",
    knownAddresses: "T. Nagar, Chennai, TN",
    phone: "+91 98765 43210",
    occupation: "Unknown",
    criminalRecord: "3 prior cases",
    priorCasesCount: 3,
    height: "5'10\" (178 cm)",
    build: "Medium",
    complexion: "Wheatish",
    hairColor: "Black",
    eyeColor: "Brown",
    identifyingMarks: "Scar on left eyebrow",
    associatedEvidence: [
      {
        id: "ev-01",
        name: "CCTV_01.mp4",
        type: "Video",
        thumbnail: "/images/cctv-suspect.jpg",
        date: "Oct 4, 2026",
      },
      {
        id: "ev-02",
        name: "Suspect_Image_02.jpg",
        type: "Image",
        thumbnail: "/images/suspects/arun-prakash.jpg",
        date: "Oct 4, 2026",
      },
      {
        id: "ev-03",
        name: "Vehicle_01.jpg",
        type: "Image",
        thumbnail: "/images/feature-image.png",
        date: "Oct 4, 2026",
      },
      {
        id: "ev-04",
        name: "Weapon_01.jpg",
        type: "Image",
        thumbnail: "/images/stats-image.png",
        date: "Oct 4, 2026",
      },
    ],
    notes:
      "Subject captured on CCTV entering through the main perimeter. Facial geometry points match with existing criminal registry files.",
  },
  {
    id: "susp-02",
    numberIndex: "02",
    name: "Karthik Selvan",
    alias: "Alias: Selva, Karthi",
    photo: "/images/suspects/karthik-selvan.jpg",
    status: "Person of Interest",
    role: "Possible Associate",
    matchConfidence: 68,
    lastSeenDate: "Oct 4, 2026",
    lastSeenTime: "08:55 PM",
    dob: "Nov 14, 1993",
    age: 32,
    gender: "Male",
    nationality: "Indian",
    knownAddresses: "Kodambakkam, Chennai, TN",
    phone: "+91 98451 22890",
    occupation: "Auto Mechanic",
    criminalRecord: "1 prior inquiry",
    priorCasesCount: 1,
    height: "5'8\" (173 cm)",
    build: "Slim",
    complexion: "Dusky",
    hairColor: "Black",
    eyeColor: "Brown",
    identifyingMarks: "Tattoo on right forearm",
    associatedEvidence: [
      {
        id: "ev-01",
        name: "CCTV_01.mp4",
        type: "Video",
        thumbnail: "/images/cctv-suspect.jpg",
        date: "Oct 4, 2026",
      },
      {
        id: "ev-03",
        name: "Vehicle_01.jpg",
        type: "Image",
        thumbnail: "/images/feature-image.png",
        date: "Oct 4, 2026",
      },
    ],
    notes:
      "Spotted in the vicinity 20 minutes prior to incident. Cell tower ping corroborates location overlap.",
  },
];
