export interface CriminalItem {
  id: string;
  criminalId: string;
  firstName: string;
  lastName: string;
  alias: string | null;
  dateOfBirth: string;
  age: number;
  gender: string;
  nationality: string;
  status: "Active" | "Inactive" | "Wanted" | "In Custody" | "Under Surveillance";
  riskLevel: "High" | "Medium" | "Low";
  crimeCategories: string[];
  linkedCases: number;
  lastKnownLocation: string;
  mugshotUrl: string | null;
  height: string;
  weight: string;
  build: string;
  hairColor: string;
  eyeColor: string;
  complexion: string;
  distinctiveMarks: string;
  aliases: string[];
}

export const INITIAL_CRIMINALS: CriminalItem[] = [
  {
    id: "1",
    criminalId: "CR-2023-001",
    firstName: "Arjun",
    lastName: "Karthik",
    alias: "Black Karthik",
    dateOfBirth: "Mar 14, 1992",
    age: 32,
    gender: "Male",
    nationality: "Indian",
    status: "Active",
    riskLevel: "High",
    crimeCategories: ["Theft", "Burglary", "Assault"],
    linkedCases: 2,
    lastKnownLocation: "Chennai, Tamil Nadu",
    mugshotUrl: "/images/suspects/karthik-selvan.jpg",
    height: "5'10\" (178 cm)",
    weight: "70 kg",
    build: "Athletic",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Wheatish",
    distinctiveMarks: "Scar on left eyebrow",
    aliases: ["Karthik A.", "Black Karthik", "AK", "Karthik"],
  },
  {
    id: "2",
    criminalId: "CR-2022-118",
    firstName: "Ramesh",
    lastName: "Kumar",
    alias: "Rocky",
    dateOfBirth: "Jul 7, 1988",
    age: 36,
    gender: "Male",
    nationality: "Indian",
    status: "Active",
    riskLevel: "Medium",
    crimeCategories: ["Assault"],
    linkedCases: 1,
    lastKnownLocation: "Coimbatore, Tamil Nadu",
    mugshotUrl: null,
    height: "5'8\" (173 cm)",
    weight: "78 kg",
    build: "Stocky",
    hairColor: "Black",
    eyeColor: "Dark Brown",
    complexion: "Dark",
    distinctiveMarks: "Tattoo on right forearm",
    aliases: ["R. Kumar", "Rocky"],
  },
  {
    id: "3",
    criminalId: "CR-2022-104",
    firstName: "Vignesh",
    lastName: "S",
    alias: null,
    dateOfBirth: "Nov 21, 1995",
    age: 30,
    gender: "Male",
    nationality: "Indian",
    status: "Under Surveillance",
    riskLevel: "Medium",
    crimeCategories: ["Fraud"],
    linkedCases: 3,
    lastKnownLocation: "Bengaluru, Karnataka",
    mugshotUrl: null,
    height: "5'9\" (175 cm)",
    weight: "65 kg",
    build: "Slim",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Fair",
    distinctiveMarks: "None reported",
    aliases: ["Vicky", "V. S"],
  },
  {
    id: "4",
    criminalId: "CR-2021-076",
    firstName: "Suresh",
    lastName: "Babu",
    alias: null,
    dateOfBirth: "Feb 3, 1986",
    age: 40,
    gender: "Male",
    nationality: "Indian",
    status: "Active",
    riskLevel: "High",
    crimeCategories: ["Cyber Crime"],
    linkedCases: 2,
    lastKnownLocation: "Hyderabad, Telangana",
    mugshotUrl: null,
    height: "5'7\" (170 cm)",
    weight: "72 kg",
    build: "Medium",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Wheatish",
    distinctiveMarks: "Mole on left cheek",
    aliases: ["Suresh B.", "Babu"],
  },
  {
    id: "5",
    criminalId: "CR-2021-053",
    firstName: "Imran",
    lastName: "Ali",
    alias: null,
    dateOfBirth: "Sep 12, 1990",
    age: 34,
    gender: "Male",
    nationality: "Indian",
    status: "In Custody",
    riskLevel: "High",
    crimeCategories: ["Drug Offense"],
    linkedCases: 1,
    lastKnownLocation: "Madurai, Tamil Nadu",
    mugshotUrl: null,
    height: "5'11\" (180 cm)",
    weight: "75 kg",
    build: "Athletic",
    hairColor: "Black",
    eyeColor: "Dark Brown",
    complexion: "Fair",
    distinctiveMarks: "Scar on chin",
    aliases: ["Imran", "I. Ali"],
  },
  {
    id: "6",
    criminalId: "CR-2020-041",
    firstName: "Dinesh",
    lastName: "M",
    alias: null,
    dateOfBirth: "Jan 6, 1993",
    age: 33,
    gender: "Male",
    nationality: "Indian",
    status: "Active",
    riskLevel: "Medium",
    crimeCategories: ["Violence"],
    linkedCases: 2,
    lastKnownLocation: "Trichy, Tamil Nadu",
    mugshotUrl: null,
    height: "5'6\" (168 cm)",
    weight: "68 kg",
    build: "Medium",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Dark",
    distinctiveMarks: "Burn mark on left hand",
    aliases: ["D. Mani", "Mani"],
  },
  {
    id: "7",
    criminalId: "CR-2020-022",
    firstName: "Prakash",
    lastName: "N",
    alias: null,
    dateOfBirth: "May 18, 1987",
    age: 39,
    gender: "Male",
    nationality: "Indian",
    status: "Inactive",
    riskLevel: "Low",
    crimeCategories: ["Arson"],
    linkedCases: 1,
    lastKnownLocation: "Salem, Tamil Nadu",
    mugshotUrl: null,
    height: "5'5\" (165 cm)",
    weight: "62 kg",
    build: "Lean",
    hairColor: "Grey",
    eyeColor: "Brown",
    complexion: "Wheatish",
    distinctiveMarks: "None reported",
    aliases: ["Prakash", "PK"],
  },
  {
    id: "8",
    criminalId: "CR-2019-167",
    firstName: "Senthil",
    lastName: "Raja",
    alias: null,
    dateOfBirth: "Aug 25, 1991",
    age: 33,
    gender: "Male",
    nationality: "Indian",
    status: "Active",
    riskLevel: "High",
    crimeCategories: ["Robbery"],
    linkedCases: 3,
    lastKnownLocation: "Tirunelveli, Tamil Nadu",
    mugshotUrl: null,
    height: "6'0\" (183 cm)",
    weight: "82 kg",
    build: "Muscular",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Dark",
    distinctiveMarks: "Tattoo on neck",
    aliases: ["Senthil", "S. Raja"],
  },
  {
    id: "9",
    criminalId: "CR-2019-089",
    firstName: "Kavitha",
    lastName: "R",
    alias: "Kavi",
    dateOfBirth: "Apr 10, 1994",
    age: 32,
    gender: "Female",
    nationality: "Indian",
    status: "Wanted",
    riskLevel: "High",
    crimeCategories: ["Fraud", "Forgery"],
    linkedCases: 4,
    lastKnownLocation: "Erode, Tamil Nadu",
    mugshotUrl: null,
    height: "5'4\" (163 cm)",
    weight: "55 kg",
    build: "Slim",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Fair",
    distinctiveMarks: "Birthmark on right wrist",
    aliases: ["Kavi", "K. R"],
  },
  {
    id: "10",
    criminalId: "CR-2018-201",
    firstName: "Mohan",
    lastName: "Das",
    alias: "MD",
    dateOfBirth: "Dec 1, 1985",
    age: 40,
    gender: "Male",
    nationality: "Indian",
    status: "Active",
    riskLevel: "Medium",
    crimeCategories: ["Smuggling", "Theft"],
    linkedCases: 2,
    lastKnownLocation: "Vellore, Tamil Nadu",
    mugshotUrl: null,
    height: "5'8\" (173 cm)",
    weight: "74 kg",
    build: "Medium",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Wheatish",
    distinctiveMarks: "Missing right little finger",
    aliases: ["MD", "Mohan D."],
  },
  {
    id: "11",
    criminalId: "CR-2018-145",
    firstName: "Arun",
    lastName: "Prakash",
    alias: "AP",
    dateOfBirth: "Jun 22, 1989",
    age: 37,
    gender: "Male",
    nationality: "Indian",
    status: "Under Surveillance",
    riskLevel: "Medium",
    crimeCategories: ["Extortion"],
    linkedCases: 1,
    lastKnownLocation: "Thanjavur, Tamil Nadu",
    mugshotUrl: "/images/suspects/arun-prakash.jpg",
    height: "5'9\" (175 cm)",
    weight: "71 kg",
    build: "Athletic",
    hairColor: "Black",
    eyeColor: "Dark Brown",
    complexion: "Wheatish",
    distinctiveMarks: "Scar on right shoulder",
    aliases: ["AP", "Arun P."],
  },
  {
    id: "12",
    criminalId: "CR-2017-092",
    firstName: "Lakshmi",
    lastName: "Devi",
    alias: "Lucky",
    dateOfBirth: "Oct 15, 1991",
    age: 34,
    gender: "Female",
    nationality: "Indian",
    status: "Inactive",
    riskLevel: "Low",
    crimeCategories: ["Pickpocketing"],
    linkedCases: 1,
    lastKnownLocation: "Kanchipuram, Tamil Nadu",
    mugshotUrl: null,
    height: "5'2\" (158 cm)",
    weight: "50 kg",
    build: "Petite",
    hairColor: "Black",
    eyeColor: "Brown",
    complexion: "Fair",
    distinctiveMarks: "None reported",
    aliases: ["Lucky", "L. Devi"],
  },
];
