import { Text, View } from "@react-pdf/renderer";
import { reportStyles } from "../styles/reportStyles";
import type { CaseReportData } from "../../types";
import { formatReportNumber, formatSimilarity } from "../utils/formatReportNumber";

export function RecognitionResultsSection({ data }: { data: CaseReportData }) {
  if (!data.recognitionResults || data.recognitionResults.length === 0) return null;

  return (
    <View style={reportStyles.section} wrap={false}>
      <View style={reportStyles.sectionHeaderRow}>
        <Text style={reportStyles.sectionTitle}>07. FACE RECOGNITION ANALYSIS</Text>
        <Text style={reportStyles.sectionBadge}>AI CANDIDATE RANKING</Text>
      </View>

      <View style={reportStyles.table}>
        <View style={reportStyles.tableHeader}>
          <Text style={[reportStyles.tableHeaderCell, { width: "12%" }]}>RANK</Text>
          <Text style={[reportStyles.tableHeaderCell, { width: "24%" }]}>CANDIDATE ID</Text>
          <Text style={[reportStyles.tableHeaderCell, { width: "28%" }]}>CANDIDATE NAME</Text>
          <Text style={[reportStyles.tableHeaderCell, { width: "18%" }]}>SIMILARITY</Text>
          <Text style={[reportStyles.tableHeaderCell, { width: "18%" }]}>STATUS</Text>
        </View>

        {data.recognitionResults.map((result, idx) => {
          const isAlternate = idx % 2 === 1;
          return (
            <View
              key={result.id}
              style={[
                reportStyles.tableRow,
                isAlternate ? reportStyles.tableRowAlternate : {},
              ]}
              wrap={false}
            >
              <Text style={[reportStyles.tableCellBold, { width: "12%" }]}>
                {formatReportNumber(result.rank)}
              </Text>
              <Text style={[reportStyles.tableCell, { width: "24%" }]}>
                {result.candidateId}
              </Text>
              <Text style={[reportStyles.tableCellBold, { width: "28%" }]}>
                {result.candidateName}
              </Text>
              <Text style={[reportStyles.tableCellBold, { width: "18%", color: "#15803D" }]}>
                {formatSimilarity(result.similarity)}
              </Text>
              <View style={{ width: "18%" }}>
                <Text
                  style={[
                    reportStyles.statusPill,
                    { backgroundColor: "#FEF3C7", color: "#92400E" },
                  ]}
                >
                  {result.status}
                </Text>
              </View>
            </View>
          );
        })}
      </View>

      {/* Mandatory Disclaimer */}
      <View style={reportStyles.warning}>
        <Text style={reportStyles.warningTitle}>BIOMETRIC RECOGNITION NOTICE</Text>
        <Text style={reportStyles.warningText}>
          Similarity scores are computational candidate-ranking results generated by biometric vector comparison. They represent probabilistic match likelihoods and require independent human verification, evidentiary corroboration, and adherence to legal identification protocols.
        </Text>
      </View>
    </View>
  );
}
