import { Text, View } from "@react-pdf/renderer";
import { reportStyles } from "../styles/reportStyles";
import type { CaseReportData } from "../../types";

export function ReportMetadataSection({ data }: { data: CaseReportData }) {
  return (
    <View style={reportStyles.section} wrap={false}>
      <View style={reportStyles.sectionHeaderRow}>
        <Text style={reportStyles.sectionTitle}>13. REPORT METADATA & LEGAL NOTICE</Text>
        <Text style={reportStyles.sectionBadge}>AUDIT RECORD</Text>
      </View>

      <View style={reportStyles.cardSurface} wrap={false}>
        <View style={reportStyles.gridTwoCol}>
          <View style={reportStyles.colHalf}>
            <View style={reportStyles.row}>
              <Text style={reportStyles.label}>Report ID:</Text>
              <Text style={reportStyles.valueBold}>{data.report.id}</Text>
            </View>
            <View style={reportStyles.row}>
              <Text style={reportStyles.label}>Version:</Text>
              <Text style={reportStyles.value}>{data.report.version}</Text>
            </View>
            <View style={reportStyles.row}>
              <Text style={reportStyles.label}>Classification:</Text>
              <Text style={[reportStyles.valueBold, { color: "#B91C1C", fontSize: 7.5 }]}>
                {data.report.classification}
              </Text>
            </View>
          </View>

          <View style={reportStyles.colHalf}>
            <View style={reportStyles.row}>
              <Text style={reportStyles.label}>Generated By:</Text>
              <Text style={reportStyles.valueBold}>{data.report.generatedBy}</Text>
            </View>
            <View style={reportStyles.row}>
              <Text style={reportStyles.label}>Generated At:</Text>
              <Text style={reportStyles.value}>{data.report.generatedAt}</Text>
            </View>
            <View style={reportStyles.row}>
              <Text style={reportStyles.label}>Integrity Status:</Text>
              <Text style={[reportStyles.valueBold, { color: "#15803D" }]}>
                Cryptographically Sealed
              </Text>
            </View>
          </View>
        </View>

        {/* AI-Assisted Analysis Notice from README Section 51 */}
        <View style={[reportStyles.noticeBox, { marginTop: 8 }]}>
          <Text style={{ fontSize: 7.5, fontWeight: 700, color: "#111827", marginBottom: 2 }}>
            AI-ASSISTED ANALYSIS NOTICE
          </Text>
          <Text style={reportStyles.noticeText}>
            AI-generated sketches and computational similarity results are provided as investigative aids. They do not independently establish identity, guilt, or legal responsibility. Investigative conclusions require appropriate human review, corroborating evidence, and applicable statutory procedures.
          </Text>
        </View>
      </View>
    </View>
  );
}
