import { ActivityItem, TimelineMilestone } from "./types";

export const MOCK_ACTIVITY_ITEMS: ActivityItem[] = [
  {
    id: "01",
    timestamp: "2026-10-05T11:32:00.000Z",
    formattedDate: "Oct 5, 2026",
    formattedTime: "11:32 AM",
    user: {
      id: "usr-01",
      name: "Arjun Karthik",
      role: "Investigator",
      avatar: "/images/avatar-investigator.jpg",
      initials: "AK",
      email: "arjun.karthik@forensix.gov",
    },
    action: "Added Evidence",
    actionType: "EVIDENCE",
    details: "Added CCTV_Footage_01.mp4 to the case.",
    category: "Evidence",
  },
  {
    id: "02",
    timestamp: "2026-10-05T10:48:00.000Z",
    formattedDate: "Oct 5, 2026",
    formattedTime: "10:48 AM",
    user: {
      id: "usr-02",
      name: "Priya Nair",
      role: "Senior Analyst",
      avatar: "/images/avatar-analyst.jpg",
      initials: "PN",
      email: "priya.nair@forensix.gov",
    },
    action: "Updated Case",
    actionType: "CASE",
    details: "Changed case status from Analysis to Under Investigation.",
    category: "Case",
  },
  {
    id: "03",
    timestamp: "2026-10-05T09:16:00.000Z",
    formattedDate: "Oct 5, 2026",
    formattedTime: "09:16 AM",
    user: {
      id: "usr-sys",
      name: "System",
      role: "Forensix AI",
      avatar: "/images/avatar-system.png",
      initials: "AI",
      email: "system@forensix.ai",
    },
    action: "AI Analysis",
    actionType: "ANALYSIS",
    details: "Generated face match analysis for suspect from CCTV footage.",
    category: "Analysis",
  },
  {
    id: "04",
    timestamp: "2026-10-04T23:46:00.000Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "11:46 PM",
    user: {
      id: "usr-01",
      name: "Arjun Karthik",
      role: "Investigator",
      avatar: "/images/avatar-investigator.jpg",
      initials: "AK",
      email: "arjun.karthik@forensix.gov",
    },
    action: "Added Suspect",
    actionType: "SUSPECT",
    details: "Added Arun Prakash as primary suspect.",
    category: "Suspect",
  },
  {
    id: "05",
    timestamp: "2026-10-04T22:28:00.000Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "10:28 PM",
    user: {
      id: "usr-02",
      name: "Priya Nair",
      role: "Senior Analyst",
      avatar: "/images/avatar-analyst.jpg",
      initials: "PN",
      email: "priya.nair@forensix.gov",
    },
    action: "Added Evidence",
    actionType: "EVIDENCE",
    details: "Added Weapon_01.jpg to the case.",
    category: "Evidence",
  },
  {
    id: "06",
    timestamp: "2026-10-04T21:55:00.000Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "09:55 PM",
    user: {
      id: "usr-03",
      name: "Raghav Menon",
      role: "Field Officer",
      avatar: "/images/avatar-officer.jpg",
      initials: "RM",
      email: "raghav.menon@forensix.gov",
    },
    action: "Updated Case",
    actionType: "CASE",
    details: "Set case priority to High.",
    category: "Case",
  },
  {
    id: "07",
    timestamp: "2026-10-04T21:20:00.000Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "09:20 PM",
    user: {
      id: "usr-sys",
      name: "System",
      role: "Forensix AI",
      avatar: "/images/avatar-system.png",
      initials: "AI",
      email: "system@forensix.ai",
    },
    action: "Facial Recognition",
    actionType: "ANALYSIS",
    details: "Potential match found: Arun Prakash (92% confidence).",
    category: "Analysis",
  },
  {
    id: "08",
    timestamp: "2026-10-04T21:18:00.000Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "09:18 PM",
    user: {
      id: "usr-01",
      name: "Arjun Karthik",
      role: "Investigator",
      avatar: "/images/avatar-investigator.jpg",
      initials: "AK",
      email: "arjun.karthik@forensix.gov",
    },
    action: "Added Note",
    actionType: "NOTE",
    details: "CCTV shows suspect fleeing towards North Boag Road.",
    category: "Note",
  },
  {
    id: "09",
    timestamp: "2026-10-04T21:15:00.000Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "09:15 PM",
    user: {
      id: "usr-02",
      name: "Priya Nair",
      role: "Senior Analyst",
      avatar: "/images/avatar-analyst.jpg",
      initials: "PN",
      email: "priya.nair@forensix.gov",
    },
    action: "Linked Record",
    actionType: "RECORD",
    details: "Linked 3 prior theft cases from State Criminal DB.",
    category: "Records",
  },
  {
    id: "10",
    timestamp: "2026-10-04T21:14:00.000Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "09:14 PM",
    user: {
      id: "usr-sys",
      name: "System",
      role: "Forensix AI",
      avatar: "/images/avatar-system.png",
      initials: "AI",
      email: "system@forensix.ai",
    },
    action: "Case Created",
    actionType: "CASE",
    details: "Case FX-2026-184 created in the system.",
    category: "Case",
  },
];

export const INITIAL_TIMELINE_MILESTONES: TimelineMilestone[] = [
  {
    id: "m-1",
    title: "Case Created",
    timestamp: "2026-10-04T21:14:00.000Z",
    formattedTime: "Oct 4, 2026, 09:14 PM",
    dotColor: "blue",
    description: "Initial case ingestion and repository record generation",
  },
  {
    id: "m-2",
    title: "First Evidence Added",
    timestamp: "2026-10-04T22:28:00.000Z",
    formattedTime: "Oct 4, 2026, 10:28 PM",
    dotColor: "blue",
    description: "Physical evidence weapon photo uploaded with SHA-256 integrity hash",
  },
  {
    id: "m-3",
    title: "Primary Suspect Added",
    timestamp: "2026-10-04T23:46:00.000Z",
    formattedTime: "Oct 4, 2026, 11:46 PM",
    dotColor: "red",
    description: "Arun Prakash designated as primary suspect following facial recognition",
  },
  {
    id: "m-4",
    title: "Latest Activity",
    timestamp: "2026-10-05T11:32:00.000Z",
    formattedTime: "Oct 5, 2026, 11:32 AM",
    dotColor: "emerald",
    description: "CCTV surveillance footage ingested and queued for AI enhancement",
  },
];
